use_frameworks!

platform :ios, '9.0'

target 'KFPageTabStripController_Example' do
  pod 'KFPageTabStripController', :path => '../'

  target 'KFPageTabStripController_Tests' do
    inherit! :search_paths

    
  end
end
